const wordList = [
    { word: "encyclopedia", hint: "A comprehensive reference work" },
    { word: "boulevard", hint: "A wide street in a city" },
    { word: "archipelago", hint: "A group of islands" },
    { word: "extraterrestrial", hint: "Originating from outside the Earth" },
    { word: "metamorphosis", hint: "A transformation process" },
    { word: "paradox", hint: "A seemingly contradictory statement" },
    { word: "surreptitious", hint: "Secretive or stealthy" },
    { word: "serendipity", hint: "Finding something pleasant by chance" },
    { word: "juxtaposition", hint: "The act of placing things side by side for comparison" },
    { word: "ephemeral", hint: "Lasting for a very short time" },
    { word: "quintessential", hint: "Representing the most perfect example of a quality or class" },
    { word: "indefatigable", hint: "Persisting tirelessly" },
    { word: "ubiquitous", hint: "Seemingly present everywhere at once" },
    { word: "epiphany", hint: "A sudden realization or understanding" },
    { word: "procrastination", hint: "The action of delaying or postponing something" },
    { word: "circumlocution", hint: "The use of many words where fewer would do" },
    { word: "euphemism", hint: "A mild or indirect word or expression substituted for one considered to be too harsh or blunt" },
    { word: "melancholy", hint: "A feeling of pensive sadness" },
    { word: "onomatopoeia", hint: "A word that imitates the sound it represents" },
    { word: "symbiosis", hint: "A mutually beneficial relationship between different organisms" },
    { word: "acronym", hint: "An abbreviation formed from the initial letters of other words and pronounced as a word" },
    { word: "catastrophe", hint: "An event causing great and often sudden damage or suffering" },
    { word: "entrepreneur", hint: "A person who organizes and operates a business or businesses" },
    { word: "integrity", hint: "The quality of being honest and having strong moral principles" },
    { word: "paradigm", hint: "A typical example or pattern of something" },
    { word: "resilience", hint: "The capacity to recover quickly from difficulties" },
    { word: "synchronicity", hint: "The simultaneous occurrence of events that appear significantly related but have no discernible causal connection" },
    { word: "ephemeral", hint: "Lasting for a very short time" },
    { word: "quintessential", hint: "Representing the most perfect example of a quality or class" },
    { word: "indefatigable", hint: "Persisting tirelessly" },
    { word: "ubiquitous", hint: "Seemingly present everywhere at once" },
    { word: "epiphany", hint: "A sudden realization or understanding" },
    { word: "procrastination", hint: "The action of delaying or postponing something" },
    { word: "circumlocution", hint: "The use of many words where fewer would do" },
    { word: "euphemism", hint: "A mild or indirect word or expression substituted for one considered to be too harsh or blunt" },
    { word: "melancholy", hint: "A feeling of pensive sadness" },
    { word: "onomatopoeia", hint: "A word that imitates the sound it represents" },
    { word: "symbiosis", hint: "A mutually beneficial relationship between different organisms" },
    { word: "acronym", hint: "An abbreviation formed from the initial letters of other words and pronounced as a word" },
    { word: "catastrophe", hint: "An event causing great and often sudden damage or suffering" },
    { word: "entrepreneur", hint: "A person who organizes and operates a business or businesses" },
    { word: "integrity", hint: "The quality of being honest and having strong moral principles" },
    { word: "paradigm", hint: "A typical example or pattern of something" },
    { word: "resilience", hint: "The capacity to recover quickly from difficulties" },
    { word: "synchronicity", hint: "The simultaneous occurrence of events that appear significantly related but have no discernible causal connection" },
    { word: "cynosure", hint: "A person or thing that is the center of attention or admiration" },
    { word: "ephemeral", hint: "Lasting for a very short time" },
    { word: "quintessential", hint: "Representing the most perfect example of a quality or class" },
    { word: "indefatigable", hint: "Persisting tirelessly" },
    { word: "ubiquitous", hint: "Seemingly present everywhere at once" },
    { word: "epiphany", hint: "A sudden realization or understanding" },
    { word: "procrastination", hint: "The action of delaying or postponing something" },
    { word: "circumlocution", hint: "The use of many words where fewer would do" },
    { word: "euphemism", hint: "A mild or indirect word or expression substituted for one considered to be too harsh or blunt" },
    { word: "melancholy", hint: "A feeling of pensive sadness" },
    { word: "onomatopoeia", hint: "A word that imitates the sound it represents" },
    { word: "symbiosis", hint: "A mutually beneficial relationship between different organisms" },
    { word: "acronym", hint: "An abbreviation formed from the initial letters of other words and pronounced as a word" },
    { word: "catastrophe", hint: "An event causing great and often sudden damage or suffering" },
    { word: "entrepreneur", hint: "A person who organizes and operates a business or businesses" },
    { word: "integrity", hint: "The quality of being honest and having strong moral principles" },
    { word: "paradigm", hint: "A typical example or pattern of something" },
    { word: "resilience", hint: "The capacity to recover quickly from difficulties" },
    { word: "synchronicity", hint: "The simultaneous occurrence of events that appear significantly related but have no discernible causal connection" }
    // Add more words as needed
];
